# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
jobs:
  web-deploy:
    name: 🎉 Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 📂 Sync files
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude=".git" --exclude=".github"
        path: /
        remote_path: /home/develo13/public_html/test
        remote_host: developertech.biz.id
        remote_user: develo13
        remote_key: ${{ secrets.DEPLOY_KEY }}

